language: node_js
node_js:
  - "8.12"

install:
  - yarn install --ignore-engines

addons:
  sonarcloud:
    organization: "conoce-tu-congreso"
    token: "$SONAR_TOKEN"

script:
  - yarn lint
  - yarn build
  - sonar-scanner

branches:
  only:
    - master
    - develop
